PROJECT_ID: semantic-layer-poc-470809    
PROJECT_NUMBER: 848806222072
REGION: us-central1
LLM_MODEL: gemini-2.5-pro

RAG_DEFAULT_TOP_K: 10  
RAG_DEFAULT_SEARCH_TOP_K: 5
RAG_DEFAULT_VECTOR_DISTANCE_THRESHOLD: 0.5
RUN_AGENT_WITH_DEBUG: True
ARTIFACT_GCS_BUCKET:  rev-eng-bkt
SESSION_DB_URL: sqlite:///./sessions.db